# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19d81aac359451d0ef218122f3b3b8ae437b141a7924bfe4dd73771b82456f8601c29f152c4b11a0092739e2d9ffa56948ab44075c6c481398ea6486c1009846

test:
  secret_key_base: 4c0a304a1ef52b89525f69884234074ef409602604afe3ae2c86d6284e0f0c946543734b5df1819b40b070cbe5dd9e210b2419df383fe9fd309923a72028a540

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
